name    'puppet-wordpress'
version '0.0.2'
source 'git://github.com/jonhadfield/puppet-wordpress.git'
author 'Jon Hadfield'
license 'Apache2'
summary 'Puppet module to set up an instance of wordpress'
description 'Installs wordpress and dependencies.'
project_page 'https://github.com/jonhadfield/puppet-wordpress'
