name    'puppet-wordpress'
version '0.0.1'
source 'https://github.com/jonhadfield/puppet-wordpress'
author 'jonhadfield'
license 'Apache'
summary 'Puppet module to set up an instance of wordpress'
description 'Installs wordpress and dependencies.'
project_page 'https://github.com/jonhadfield/puppet-wordpress'
